name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@5.189.237.171
      DEPLOY_DIRECTORY: /root/apps/url-shortener
      CONFIG_PATH: /root/apps/url-shortener/config/prod.yaml
      ENV_FILE_PATH: /root/apps/url-shortener/config.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0  # Получаем всю историю для работы с тегами

      - name: Verify tag exists
        run: |
          if ! git rev-parse "${{ github.event.inputs.tag }}" >/dev/null 2>&1; then
            echo "::error::Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Build app
        run: |
          set -e
          go mod download
          go build -o url-shortener ./cmd/url-shortener

      - name: Install dependencies
        run: sudo apt-get install -y ssh rsync

      - name: Prepare SSH key
        run: |
          set -e
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Create remote directory
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} \
            "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"

      - name: Sync files
        run: |
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' \
            --exclude='.git' \
            --exclude='deploy_key.pem' \
            ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}

      - name: Verify deployment files
        run: |
          if [ ! -f "./deployment/url-shortener.service" ]; then
            echo "::error::Service file not found in deployment directory"
            exit 1
          fi

      - name: Setup service
        run: |
          set -e
          scp -i deploy_key.pem -o StrictHostKeyChecking=no \
            ./deployment/url-shortener.service \
            ${{ env.HOST }}:/tmp/url-shortener.service
          
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} \
            "mv /tmp/url-shortener.service /etc/systemd/system/url-shortener.service && \
            systemctl daemon-reload"

      - name: Configure environment
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} \
            "touch ${{ env.ENV_FILE_PATH }} && \
            chmod 600 ${{ env.ENV_FILE_PATH }} && \
            echo 'CONFIG_PATH=${{ env.CONFIG_PATH }}' > ${{ env.ENV_FILE_PATH }} && \
            echo 'HTTP_SERVER_PASSWORD=${{ secrets.AUTH_PASS }}' >> ${{ env.ENV_FILE_PATH }}"

      - name: Restart service
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} \
            "systemctl restart url-shortener.service"

      - name: Cleanup
        run: rm -f deploy_key.pem